### ISSUE TITLE
Tidy up readme

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#351]
Remove todos, add relevant information where needed etc.

**Comment by Nuanda** [comment]
Add a short introduction what is BIP, who owns it and who provided the current version. Consult with @wjurkowski the final wording and LICENSE, in case he'd like to have it spelled differently.

**Comment by Nuanda** [comment]
@wjurkowski What license for BIP you'd like to have? No license file means, more or less, "one cannot do anything with that apart from looking at it" (at least that is the "common interpretation"). If you'd like other contributors, or you'd like to allow them to fork this project, a license would be needed.

**Comment by wjurkowski** [comment]
I assumed  we have some default license on github. We need license that ask
for acknowledgement of our work and allows reusing the code to other
projects for non-commercial use

2015-07-22 11:29 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Basically OS licences do not deal with the kind of use (whether commercial or non-for-profit) - they rather deal with contributions and distribution: whether one needs to acknowledge that TGAC owns the unmodified version (and what was modified) and whether the modified result needs to be OS as well or not.

For instance the GPL licence is considered both 'viral' (no closed source derived work possible) and it requires proper authorship attribution: http://opensource.org/licenses/GPL-3.0

Other OS licences: http://opensource.org/licenses

Please also check if the current README preamble is ok with you.

**Comment by wjurkowski** [comment]
GPL-3.0 sounds fine plus we will add necessary info in README

2015-07-22 12:02 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Adjusted - please tell me if this is what you meant.

**Comment by Nuanda** [comment]
@wjurkowski Wiktor, as that might not be clear :), I mean the text that appears here https://github.com/eSpectrum-IT/brassica just below the table.

**Comment by wjurkowski** [comment]
I know, thanks. I'm going to modify this section later.

2015-07-23 8:59 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
Reassigning it to you, then.

**Comment by teatree1212** [comment]
Which CropStoreDB version is the BIP based on? Currently it is version 7.0.00 ( Last update July2015).

**Comment by Nuanda** [comment]
@wjurkowski I guess you need to answer this, as we only got the DB dump (from you).

**Comment by wjurkowski** [comment]
Not sure if the actual version number but definitely is pre-July 2015. Let's ask Graham K. for details

**Comment by teatree1212** [comment]
Readme updated
