### ISSUE TITLE
Cache invalidation (touch) does not work for models related through an intermediate

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#485]
Example: TraitScores' table show PP.name - if one changes the PP in question visibility to private, TraitScores table will still show its name.

**Comment by kammerer** [comment]
It seems that Trait Scores' table does not show PP.name anymore, so this is not a problem. The only other case I identified is LinkageMap <-> PlantPopulation <-> TaxonomyTerm (not critical, since taxonomy terms are not supposed to change under normal circumstances).
