### ISSUE TITLE
Design of interactive scoring data template generation

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#502]
@kammerer Tomasz, as discussed in #488, there is an idea to introduce what we call 'step 2.5' of the Trial submission. This step would be a form which asks the user a set of questions, and then creates a CSV template, to be later used by the user to submit scoring data (current step 3).

Do you think that we should extend the number of steps to 5, in order to accommodate that, or could we simply start the 3rd step with the form, and then create the template and show the upload button? That would make this step having three individual "substages", but all of them closely related.

**Comment by teatree1212** [comment]
I will design a template based on standard experimental designs. it may be similar to this one used for SRA sequence submissions:
[SRA_BioSample_template.xlsx](https://github.com/eSpectrum-IT/brassica/files/263131/SRA_BioSample_template.xlsx)

**Comment by teatree1212** [comment]
see draft here
https://docs.google.com/spreadsheets/d/1hg4yUOGzzYZ5Yolx02dQ4OBBwQERAQU1gmoo10ZgfoQ/edit#gid=0

**Comment by Nuanda** [comment]
@kammerer What @teatree1212 designs here will eventually be the output of the CSV template generation process. But please tell me what you think about the original question (the wizard/UX side to the issue).

**Comment by kammerer** [comment]
I think adding another step would probably be easier than step 2.5 (which would require more custom javascript code). It should not be a big problem to change the number of steps only for trial submission.

**Comment by Nuanda** [comment]
@kammerer Thanks. I tend to agree with that option as well. Let's wait a bit with that task, since we still don't know if accessions are required or not.

**Comment by kammerer** [comment]
@Nuanda If we do the work required to vary number of steps for different submission types then I would also suggest splitting the first step and putting location-related fields on a separate page. The first step is big and there are required fields in two places quite far from each other.

**Comment by Nuanda** [comment]
@kammerer I'd rather not. True, it is a bit long, but all that is logically related.

**Comment by Nuanda** [comment]
@teatree1212 Before we go with the design matrix "2.5 step", please have a look at the following columns in the PlantTrial table:
  - `design_type`, with values like:
    - "randomized blocks"
    - "incomplete block design"
    -  "alpha design"
    - "randomised complete block design with restricted blocking for spring types"
    - "randomised complete block design"
  - `statistical_factors`, with values like:
    - "occasion / bench / block / plot / pot"
    - "occasion / replicate / block / plot / pot"
    - "replicate / area-pair / block / plot"
    - "occasion / replicate / area-pair / block / plot"
    - "rep = block / plot"
    - "treatment / rep / block / plot"
  - `design_factors`, with values like:
    - "rep / block / row / column / plot"
  - `design_layout_matrix`, with values like:
    - "df.RRES_2001 df.RRES_2036 df.RRES_2037 df.RRES_2072 ...." (a long list of DesignFactor.design_factor_name, being essentially foreign keys to the DesignFactor table).

All of them also sometimes have nulls as value.

I think all these columns are somehow related to both the experiment design, and the type of data (raw/mean) being submitted. What should we do with these?

**Comment by teatree1212** [comment]
I am currently studying the different experimental trial designs field/greenhouse/growth chamber trials can have. I think this would be part of the submission template I am working on and I will try and map the database fields to the column names/ rename the column names in that template.

**Comment by Nuanda** [comment]
@teatree1212 What I mean - perhaps we should use these PlantTrial fields to write down the experiment design?

**Comment by Nuanda** [comment]
@teatree1212 Regarding the template you prepare, here are my ideas:
 - I think we should **require** something like `sample_id` - it would be a valuable piece of information for the users to be able to track particular scores back to a single plant in their experiment (note that Block/Pot/Rep identification is optional); also, we need to name the created PSU record somehow ;)
 - I understand `plant_accession` and `originating_organisation` are subject to discussion in #500 
 - I think we have decided to "promote" PlantPart from individual PSU level to more general TD level - hence we would not need `Plant organ/tissue` here: or does this column have some different meaning?

**Comment by teatree1212** [comment]
@Nuanda , second to last comment: "use these PlantTrial fields to write down the experiment design? "
they are already part of the first submission step. Do you want to switch that to step 2.5? It  might make more sense in that submission category.. But let's wait until I can say more in #488 .

@Nuanda , last comment:
sample_id now compulsory in the template ( still a working document as we are still discussing experimental design issues)

I commented on this in issue #500 relevant here: that plant_accession and originating_organisation will always  be a compulsory part of the interactive scoring template.

Sorry, Tissue/PlantPart , yes you are right. I did this together with some experimentalists and they wanted plant part there, but it is part of the trait, so not necessary actually.  (also relevant  for issue #416  assuring this is closed and decided )

**Comment by Nuanda** [comment]
@teatree1212 Yes - my idea was to let the user pick the experiment design in step 2.5, with the checkbox selection set, and then to automatically construct the value for the `design_factors` column above (we would remove it from the earlier submission step). This way there is less chance for the user to write meaningless data there, and we are able to use that information to properly construct the CSV template.

**Comment by teatree1212** [comment]
I think I may have commented on the wrong thread. Relevant for this discussion is my newest comment in #488 , which hopefully lets us ( you (: ) go further with this now.

**Comment by Nuanda** [comment]
@teatree1212 Actually, does `plant_accession` make sense for non-raw (mean) data submission? Do the experimentallists compute means only for same-accession plants?

**Comment by teatree1212** [comment]
yes. An Accession in Plant-Scientific terms is a certain plant type.

**Comment by Nuanda** [comment]
All right - so a CSV scoring template generated for non-raw data submission, should also have the `plant_accession` and `originating_organisation` column headers?

**Comment by teatree1212** [comment]
yes. If you have a look at the .csv, i colour-coded the compulsory and optional fields. ( orange vs blue). I  just specified it even more in the text above the headers.

**Comment by teatree1212** [comment]
can you remind me of where the technical replicates are going to be stored vs the biological replicates? Biological: design_factor_n -for "rep"
technical: TraitScore.replicate_score_reading?

**Comment by Nuanda** [comment]
Biological - yes, design_factor.

Technical - TraitScore.technical_replicate_number (we decided to rename that column a bit) - since "reading" suggests the actual value that's been measured, and this is just the (ordinal) number of a tech repl.

**Comment by Nuanda** [comment]
So, for processed data we don't have the 2.5 step, or, rather, we have it in a trivial form: downloading a ready template. Both declaring the technical replicate numbers and the design factors are for raw data only.

@teatree1212 Do you think we are able to proceed with implementing that?

**Comment by Nuanda** [comment]
#481 is the "implementation" task to add support for PA's two fields to the scoring upload step.

**Comment by teatree1212** [comment]
you are right, the 2.5 step is only for raw data- kind of- where do you specify the information on processed data? As in the nature of the mean? 
I suppose the ontologies- if available can just be added.
please go ahead with the changes! 
Will these fields and connections also be applicable to the API? How long do you think will this development take? We have someone who wants to upload datasets soon.

**Comment by Nuanda** [comment]
All DB-related changes (added/deleted columns, mandatory restrictions, relations between tables) are applicable to the API, since this is the same DB (both the data model/schema and the actual data).

What do you mean by "this development"? Roughly, we need to:
 1. extend the first step with the raw/mean switch, or ontology selection, or something similar
 1. let the user submit accessions
 1. extend PlantAccession to relate to PLs
 1. decide and implement heuristics on how to relate an accession to either PV or PL
 1. develop the 2.5 interactive step, the new template and an extended parser for that template
 1. develop the plant overview image upload part

This is more or less what needs to be done for the new plant trial submission.

**Comment by Nuanda** [comment]
NOTE to self: #523 is an implementation task for technical replicates "back-end" side.

**Comment by Nuanda** [comment]
@teatree1212 I've just realised that there is a single question we need to ask the user both for raw and for processed data - the PL/PV distinction. After reading #481 again I understand that a single trial submission may use _either_ PlantLines _or_ PlantVarieties in order to identify the genetic material used. I mean, there are no trials/submissions, where we are going to have, in a single column, mixed, both PLs and PVs, right? And, what is important, if a given name is not found either in the PL table or in the PV table, there is no way of telling, without asking to user, what should we do (i.e. whether to (a) create a new PV, or to (b) ask the user to submit a new PL via the PlantPopulation submission first).

If my understanding is correct, I think we may simply add a question to our "2.5 step" that will explain our understanding of both terms (Plant Lines vs. Plant Varieties), and it will ask the user which one's (PL's or PV's) name s/he is going to upload in the scoring sheet.

So, in that case, this question is going to be present for both raw and processed data submission.

Am I correct?

**Comment by teatree1212** [comment]
correct, the question is relevant to both raw and processed data. 

Unfortunately, in some experiments there are both lines and varieties used. So somehow either the database needs to recognise them as such and put them to the right place, or the user needs to specify. Given the current state of our list of varieties described in #448 , we have to make the user define this, correct.

If we take for example the OREGIN dataset to be imported at some point,I could see 2 Line names in there. That is not much, but it can happen that some experimentalists just add a couple of their favourite lines to an experiment for fun... ( fun..).
<img width="806" alt="screen shot 2016-06-15 at 14 56 09" src="https://cloud.githubusercontent.com/assets/17452217/16082513/91cfe620-3309-11e6-8aa6-30f02eb8f37f.png">

We could make them submit them separately S: Or divide Cultivar and Line into two columns in our template and hope people follow the instructions..

**Comment by Nuanda** [comment]
As I wrote elsewhere, this is difficult given the current heuristics we decided to implement. Which is to add any new PV if not found, but _not to_ add any PLs, if not found (but rather ask the user to use the PP submission to create these PLs first).

When I don't know beforehand if a given value is (meant to be) a PV or a PL, and I cannot find it either in plant_lines or in plant_varieties tables, I can no longer tell if I should make it a new PV or ask the user to submit it as a new PL.

**Comment by teatree1212** [comment]
true. This protection against wrong data assignment is gone with adding the additional relation between accession and Varieties. I can't see a different way other than having two separate columns in the submission spreadsheet and make it a requirement that one of them (only) is filled out.

**Comment by wjurkowski** [comment]
But these two columns will not be needed if the submission was set up correctly. I think this is something we should not allow in the future. Could asking to create new PLs before continuing be an option?

**Comment by Nuanda** [comment]
This is exactly how it is done now - we ask the user to create new PLs using the plant population submission wizard (s/he can also always do that using the API).

**Comment by teatree1212** [comment]
@Nuanda Can you by the 3rd of August add a default "comments" column to the interactive trait scoring template and parse the content in there to trait_scores.comments ? The "comments" columns could appear as the very last column in the spreadsheet, or in front of the trait definitions- the former is preferred.

**Comment by Nuanda** [comment]
@teatree1212 I asked a question about that in #544 a couple of days ago - let's keep that discussion in that other thread.

**Comment by Nuanda** [comment]
@teatree1212 Going back to the original question - for now I assume we will ask the user to use two distinct columns (one for PV name, another for PL name) if s/he chooses (in the template definition, aka "2.5", step) that **both** PVs and PLs are being used in this particular submission.

Or maybe you have some fresh ideas about how to handle that using a single column?

**Comment by wjurkowski** [comment]
We could have it in one column assuming that the uploaded content would be
checked against combined dictionary of known PL and PV. If the user would
hit something unknown they would need to define it irrespective of them
being submitted as one column or two.
Could you remind what is the current strategy to deal with new PL and PV?

2016-09-28 13:46 GMT+01:00 Tomasz Gubała <notifications@github.com>:

**Comment by Nuanda** [comment]
I would rather refer you to my "Status Report no 16" email (21.06.2016) since it's a long post to repeat it again here ;).

**Comment by wjurkowski** [comment]
OK, thanks for reminder, I wasn't sure if the process is interrupted in bot PL and PV cases. In light of this what is the rationale to keep two columns in submission?

**Comment by Nuanda** [comment]
The rationale is that currently BIP cannot discern between new PL and new PV - both are just unknown words (names) to it, and BIP is not able to decide whether to create a new PV with that name, or tell the user to submit a new PL with that name.

Anyway, I propose to put that on hold. It is because we plan to pursue the Population submission refurbishment shortly, and afterwards it may easily appear that this feature here is not needed at all (for instance, we will move all PL, PV and PA creation there and only require that PT scoring refer to already existing PAs).

**Comment by Nuanda** [comment]
@teatree1212 Annemarie, apart from the PL/PV name issue we are discussing - is there anything more in this thread which is still needed and not provided already (or described in separate issues)?

**Comment by Nuanda** [comment]
So, PL, PV and PA creation is now possible through the Plant Population submission procedure. Can we close this issue, then?

**Comment by wjurkowski** [comment]
Yep! Thanks!
