### ISSUE TITLE
Originating organisation for 288 Plant Accessions

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#568]
We have 288 Plant Accessions which do not have an originating organisation. Since we started to require that value (OO) for new accession, it would be even better if we could set OO for all present values of PA.

All these 288 PAs have the following `plant_accession` column values:  "rres_GK090855", "rres_GT080921", "rres_GT090261", "rres_GK090235", and so on. All of them are either 'rres_GK' or 'rres_GT' followed with a number.

According to CS data all of them were "entered_by" Pierre Carion (BBSRC), "confirmed by" Jackie Barker (BBSRC) and, as "accession_originator" (?) they have either Jackie Barker or Graham Teakle (Warwick).

Annemarie, are you able to assign an originating organisation for these PAs?

**Comment by teatree1212** [comment]
RRes is Rothamsted as originating organisation. You can put that into any column that has an accession with  rres in the Accession name
