### ISSUE TITLE
Changes in BIP links to reflect the TGAC -> EI transition

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#571]
I've just realized TGAC is no more, long live the EI. Some links from inside the BIP are no longer working (Sarah's webpage, Wiktor's Group etc. etc.).

I also understand the new EI webpage is still under construction. Please notify me when things are more or less settled down there, so I can update the web links inside the BIP.

**Comment by teatree1212** [comment]
TGAC has changed its name and logo to Earlham Institute.
Therefore, please change the footer section to
Earlham Institute ( same adress)
replace TGAC logo with EI logo
change email adresse: bip@earlham.ac.uk

can you also change the URL, but have the old one link to the new address?
bip.tgac.ac.uk/ to bip.earlham.ac.uk

new links to people involved
Wiktor: http://www.earlham.ac.uk/wiktor-jurkowski
Annemarie: http://www.earlham.ac.uk/annemarie-hildegard-eckes
Sarah Ayling doesn't have a website

**Comment by Nuanda** [comment]
Name change can only be made by TGAC/EI IT administrators. But it is worth doing only after we get the SSL/HTTPS certificate for the new domain name (bip.earlham.ac.uk).

@wjurkowski What affiliation should I put by Sarah's name? Simply "Earlham Institute"?

**Comment by Nuanda** [comment]
I've moved server name change stuff to #581. The rest should be doable without EI system admin cooperation.

**Comment by wjurkowski** [comment]
The links should be all stable: 
Annemarie http://www.earlham.ac.uk/annemarie-hildegard-eckes
Wiktor http://www.earlham.ac.uk/wiktor-jurkowski

Could you change TGAC to Earlham Institute - no group names 
Sarah no link - just leave the institute name

**Comment by wjurkowski** [comment]
Could the link be at the end, after afilliation and email address?
e.g. Wiktor Jurkowski, Earlham Institute, http://www.earlham.ac.uk/wiktor-jurkowski
Sarah Ayling, Earlham Institute, sarahcdyer@gmail.com
It will look more consistent this way in case someone doesn't have a link
