### ISSUE TITLE
testupload through wizard

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#573]
I have just done a test upload through the wizard in preparation for the proper upload of the first datasets coming up very soon. I realised that a few things need to be changed:

1) When submitting new trait definitions, it is possible to add new traits based on what is available in Trait Ontology. However, if that trait is not available in Trait Ontology, there is no possibility for the user to specify their own trait name. Therefore, please have, in a similar manner to the "Units of measurements" definition, add an OR and "please enter new trait name"

2) Question: If the users specify a population, but not all their lines they submit values for are part of that population, will that be a problem?

3) Question2: if some single values are empty
<img width="529" alt="screen shot 2016-07-05 at 10 53 32" src="https://cloud.githubusercontent.com/assets/17452217/16580940/dc0249dc-429e-11e6-8d92-502d6fce91e2.png">

**Comment by Nuanda** [comment]
@teatree1212 

1. There are not only TO terms in the Traits table. I have also added all terms curated and prepared by you in the google docs table. So, the most immediate "solution" to the August submissions issue would be to simple send us the term names (and their descriptions) for the traits measures in these submissions and we will add them to the Traits table. Later, we can think of a solution when a user is able to extend the trait vocabulary.

2. There is no such requirement. Plant Lines may belong to different Plant Populations for a single trait scoring submission.

3. If there is a missing trait score, no value will be recorded, but all other values for the given Plant Scoring Unit should be recorded.

**Comment by teatree1212** [comment]
Thank you for the info. Shall we close this for now and discuss a solution on trait vocabulary extensions in another issue later?

**Comment by Nuanda** [comment]
All right.
