### ISSUE TITLE
Migration to new server name in the Earlham Institute domain

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#581]
Requires:
 - the new SSL cert
 - DNS IP setup
 - old DNS name redirection
 - couple of changes in BIP code
 - ORCID setup change.

**Comment by Nuanda** [comment]
@wjurkowski Wiktor, please tell the system administrators on your side to put the new SSL certificate and the key for _bip.earlham.ac.uk_ in the root user home directory on the BIP server, and notify us it's done. We will take it from there.

**Comment by teatree1212** [comment]
sent request to System administrators
