### ISSUE TITLE
API POST status "500", instead of an error message, when sending arrays in JSON

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#595]
Why do I get this error message when posting my list to
https://bip.tgac.ac.uk/api/v1/plant_varieties 
## I am using Postman

{
  "plant_variety": [
  {
    "plant_variety_name": "Remy",
    "crop_type": "Modern winter oilseed rape"
  },
  {
    "plant_variety_name": "Robust",
    "crop_type": "Modern winter oilseed rape"
  },
  {
    "plant_variety_name": "Alaska",
    "crop_type": "Modern winter oilseed rape"
  },
  {
    "plant_variety_name": "Pirola",
    "crop_type": "Modern winter oilseed rape"
  },
  {
    "plant_variety_name": "Milena",
    "crop_type": "Modern winter oilseed rape"
  },
  {
    "plant_variety_name": "Allure",
    "crop_type": "Modern winter oilseed rape"
  }
  ]
  }

**Comment by Nuanda** [comment]
@teatree1212 Arrays are not accepted, you need to post varieties one by one. Normally, when using a programming script, you would do that in a kind of "for" loop. I almost finished my client script example, I hope to show it to you soon.

@kammerer Tomasz, the API should not fail on these calls - it should simply return some valuable error message to the user. Please try to detect such a case and issue an error message.
