### ISSUE TITLE
population_submission.rb

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#600]
I don't understand how you could create just one  pluralize_class method that defined the 
create_record method  which you use for both creating all new records for all tables.

I am referring to the part below which you use within the create_record  method 
here, the class_name is defined as plant_variety?plant_varieties:variety_name
which would be part of the API request.

+def pluralize_class(class_name)
 +  class_name == 'plant_variety' ? 'plant_varieties' : "#{class_name}s"
 +end

**Comment by Nuanda** [comment]
This is needed because of English inflection. For all nouns I use in the example, adding "s" makes the form plural (plant_score -> plant_scores). The exception is PV (plant_variety -> plant_varieties) - hence this code. It simply finds out if it is the special case or the standard "s" case.

This function (it's not a class) simply turns `something` into `somethings` apart from the case, when it is `plant_variety`, then it turns it into `plant_varieties`.

**Comment by teatree1212** [comment]
oh I see!

**Comment by teatree1212** [comment]
I have got this idea of submitting the plant_varieties and then recording them to retrieve the ids and adding them to the plant_line submission so that they are linked. For that , I am using part of your script where you submit plant varieties. after that is run, I need to record the ids of all Plant-varieties( which now are all in BIP) , for that I want it go over all the plant_variety_names again and record them in a list. is this sufficient or is this just a variable? I don't know what the [o] stands for in  "response['plant_varieties'][0]['id']"  lines

request = Net::HTTP::Get.new("/api/v1/plant_varieties?plant_variety[query][plant_variety_name]=#{URI.escape plant_variety_name}", @headers)
  response = call_bip request
  record_ids = response ['plant_variety']['id']

**Comment by Nuanda** [comment]
So, if you need to submit `plant_population`, `plant_accession`, `plant_line` and `plant_variety` - you can easily use the `create_record` function I wrote - just copy it over to your script file. You will also need to copy `test_error`, `call_bip` and `pluralize_class` functions.

For `plant_variety` you can even directly re-purpose my `record_plant_variety` function - it will either find the variety in BIP (and tell you its id) or it will create it, and also return its id. Only remember you need to extend the `create_record('plant_variety', plant_variety_name: plant_variety_name)` call with additional parameters, if you want to set more attributes of the varieties.

**Comment by teatree1212** [comment]
But i need to link them together? so When creating the plant_variety record, I need to record the varitey_ids and submit them with the appropriate plant_lines

**Comment by Nuanda** [comment]
1. Perhaps it would be easier and faster for you to send the varieties data too @nowakowski, he will record it for you (and all future users) in the BIP.

2. If you, however, want to do that by yourself, you can do that via the API. I don't think you need ids of the submitted varieties, if you want to use them in the manual plant population submission wizard - the form over there lets you pick a variety giving its name. So no need to record ids.
![mbb_screenshot1](https://cloud.githubusercontent.com/assets/107565/16873204/f6600972-4a91-11e6-95af-f4134d7bf588.png)

**Comment by teatree1212** [comment]
I see. Plant_variety_names are actually recorded in the plant_lines table. Okay, I will submit with parts of your script. expect more questions (:

**Comment by Nuanda** [comment]
When registering a `plant_variety`, do you assign any other values apart from the `plant_variety_name`?

**Comment by teatree1212** [comment]
create_record('plant_variety', plant_variety_name: plant_variety_name,
    crop_type: accession_type )

**Comment by teatree1212** [comment]
or rathe ACCESSION_TYPE as it is the header of the column?

**Comment by Nuanda** [comment]
Ok, so in this case you need a slightly modified version:

```
def record_plant_variety(plant_variety_name, crop_type)
  request = Net::HTTP::Get.new("/api/v1/plant_varieties?plant_variety[query][plant_variety_name]=#{URI.escape plant_variety_name}", @headers)
  response = call_bip request
  if response['meta']['total_count'] == 0
    create_record('plant_variety', plant_variety_name: plant_variety_name, crop_type: crop_type)
  else
    response['plant_varieties'][0]['id']
  end
end
```

and then, you call that function in a loop like this:

```
plant_variety_id = record_plant_variety(row[VARIETY], row[CROP_TYPE])
```

where VARIETY is the index of the variety name column in your CSV, and CROP_TYPE is the index of the crop type column in your CSV.

**Comment by teatree1212** [comment]
for creating the plant_population, which I just do once, I just use your create_record function in this fashion, right?
 puts '   - Creating experimental plant_population '

 create_record('plant_population',
   name: 'RIPR_test_population',
   description: '
387 Brassica napus accessions used in the RIPR project for which mRNAseq data were submitted to SRA under PRJNA309367
',
   establishing_organisation: 'York University',
   taxonomy_term_id: 71  #this is Brassica napus id in BIP
 )

**Comment by teatree1212** [comment]
I suppose I have to wrap a function around it like this
def record_plant_population(name,description,establishing_organisation,taxonomy_term_id)
create_record..
end

**Comment by Nuanda** [comment]
I think the former example should work: `create_record('plant_population', name: .... other data)`. Just remember it does not check if the population exists first - so if it does, you'll get an error.

**Comment by teatree1212** [comment]
can you explain to me how I can use plant_variety_id from
plant_variety_id = record_plant_variety(row[VARIETY], row[CROP_TYPE])
as my actual plant_variety_id? i have a feeling this 
uses the function record_plant_variety
but then does not  extract the plant_variety_id part from the response, which I want to use in my plant_ line record

**Comment by Nuanda** [comment]
Hmm, perhaps it would be easier to us if we see the shared code. Are you familiar with the idea of branches and pull requests in git/github?

**Comment by teatree1212** [comment]
I know the basics. I don't have this repository on my computer, I suppose I would have to start with that?

**Comment by Nuanda** [comment]
All right, never mind that. If you get the plant_variety_id (it should be a number) that it is this PV's identifier in the BIP db. Now, when you create a plant line, which should be related to this PV, inside it's attributes, you will add this mapping: `plant_variety_id: plant_variety_id`.

**Comment by Nuanda** [comment]
If you _do not_ get a number in the `plant_variety_id` variable it might be due to some error - do you get any error message in the console where you run the script?

**Comment by teatree1212** [comment]
let me do a branch. give me 2 sec.

**Comment by teatree1212** [comment]
checkout Branch V1
I created a folder in public/population_submission

**Comment by Nuanda** [comment]
The branch is there but I think you still need to commit changes and push them.

**Comment by teatree1212** [comment]
oh one sec..

**Comment by teatree1212** [comment]
now?

**Comment by Nuanda** [comment]
You have committed that and pushed directly to master. But don't worry - it's a client script, it won't break anything. Let me see...

**Comment by teatree1212** [comment]
S: sorry

**Comment by teatree1212** [comment]
About the file: I know that I am not calling the functions yet, but I don't know in what context I would do that and how.

**Comment by Nuanda** [comment]
I see that you removed the branch. We will need it so let me create one anyway :).

**Comment by teatree1212** [comment]
(:

**Comment by Nuanda** [comment]
I made a PR #601 - see you there ;).
