### ISSUE TITLE
Checking and reporting for encoding/format-related parsing issues

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#604]
I get an error message that the file format is not correct for the upload of test raw data submission. As Github doesn't support csv filetypes, I am sending the problematic sheet via email so that it remains unaltered.

![screen shot 2016-07-22 at 10 44 57](https://cloud.githubusercontent.com/assets/17452217/17053357/7538e7b6-4ff9-11e6-8b75-3de7f35eea95.png)

**Comment by Nuanda** [comment]
I think it's again the coding. Are you sure you save the file in UTF-8 encoding? I see two variety names in "strange" encoding.

**Comment by teatree1212** [comment]
Oh okay. Is it possible to have a -checklist error message? 
-check your file is in the right format (csv)
-check spelling of your headers
-check spelling in your columns, pay attention to words with special characters

**Comment by kammerer** [comment]
CSV uploads are replaced with XLS which should prevent such issues as the pregenerated templates are easier to use.
