### ISSUE TITLE
elasticsearch_development environment

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#606]
I am trying to run the elastic search, which is one of the steps to set up the DevEnv
https://docs.google.com/document/d/1KYbVoAaGmiBAPYbg1OY8jKHeJrC9LRnuSwigEFOVuW8/edit
it has been running for a long time now but nothing has changed for an hour -last message was this:
[2016-07-25 09:32:13,590][INFO ][cluster.routing.allocation] [Baron Macabre] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[brassica_development_trait_descriptors][1], [brassica_development_trait_descriptors][1], [brassica_development_trait_descriptors][4]] ...]).

I have tried last Friday to run elastic search and it ran longer, but stopped at some point. 
I thought it had stalled and stopped the process. ( have a look at the document).
[dev_env_setup_log.txt](https://github.com/TGAC/brassica/files/381146/dev_env_setup_log.txt)

Is there anything wrong or should I keep waiting and if there is something wrong what is the next step?

And, personal interest, who came up with man-ape and baron macabre?

**Comment by Nuanda** [comment]
ElasticSearch is a popular indexing service developed externally, so I have no idea who came up with the macabre. The server is intended to keep running in the background all the time so there is nothing special to wait for. If it's not working properly then your 'app:bootstrap' step will fail. If that one works ok, ES should be ok as well.

Please note the app:bootstrap step will take a while.

**Comment by Nuanda** [comment]
I assume it worked and we can close this issue now.
