### ISSUE TITLE
Deployment slow due to reindexing

### ISSUE THREAD

**Issue by kammerer** [TGAC/brassica#615]
Right now ES indices are reindexed on each deployment and that takes quite long time. However reindexing is not always necessary - it is needed only when we change the fields to be indexed. Two solutions come to my mind:

* enforce indexing on deployment with a special flag (skip it by default)
* enqueue indexing to be performed asynchronously after the deploy is completed 

@Nuanda WDYT?

**Comment by Nuanda** [comment]
A flag would be much preferred for me.
