### ISSUE TITLE
Consider asynchronous index updates

### ISSUE THREAD

**Issue by kammerer** [TGAC/brassica#621]
1. Index update caused by saving submitted objects can easily take a few seconds during which user waits for the request to be completed.
2. Indexing issues may cause request to look like it failed while the main work had been performed correctly. 

Note that depending on load using delayed job for this task may not be optimal.

**Comment by kammerer** [comment]
@Nuanda An idea to consider.

**Comment by kammerer** [comment]
@Nuanda Actually, after working with data provided by Annemarie I have to say that ES optimization is crucial (perhaps we can employ other means along with/instead of async indexing). Right now the request for making submission public easily takes minutes and often results with gateway timeout (despite having increased it in nginx configuration).

**Comment by Nuanda** [comment]
@kammerer Is this occur only for publishing private submission, or also for finalizing a submission as public?

**Comment by kammerer** [comment]
Finalization of public submission is affected in the same way. What is more, event finalization of private submission can take a lot of time, but this is most likely caused by something else (as it should not touch ES indices). I will add another issue about that.

**Comment by Nuanda** [comment]
Have you perhaps investigated if this is not connected with lookup times? Per each record we perform a series of searches for PLs, PVs, PAs etc. I think these should be quite fast though maybe some queries are broken in a way?

**Comment by kammerer** [comment]
I did not investigate this too much. Actually, I am not sure now how I came up with conclusion that ES is to blame. Perhaps this is wrong assumption. Anyway, before we attempt to optimize it we should do some profiling.

**Comment by Nuanda** [comment]
It looks like there's something wrong with the "touching" mechanism - it happens when I try to `update` a PA which has a lot of PSUs attached. Even 112 PSUs is already a problem (takes a lot of time). "hzau2004_TN018_a04" is an example of such an accession.

**Comment by Nuanda** [comment]
#625 is probably related.

**Comment by Nuanda** [comment]
No longer considered a bug - the real problem (touch cascade) was removed in #649
