### ISSUE TITLE
CSV parsing error with Windows generated CSV

### ISSUE THREAD

**Issue by kammerer** [TGAC/brassica#624]
Uploading hand-edited CSV from Windows resulted in unhandled exception:

`CSV::MalformedCSVError (Unquoted fields do not allow \r or \n (line 2).)`

TODO:
- [x] better exception handling for upload action
- [x] more flexible CSV parser

**Comment by kammerer** [comment]
False alert - the exception was caused by my mistake in formatting the file. Properly formatted file with Windows line breaks is parsed correctly. Still, better handling of unexpected errors would be nice as right now the app just seems to freeze with disabled upload button.

**Comment by Nuanda** [comment]
#604 is related to this.

**Comment by kammerer** [comment]
Submission uploads are changed to XLS. CSV parser used for GWAS handles inconsistent line-breaks better. General error handling for uploads is also improved.
