### ISSUE TITLE
401 Unauthorized response from Zenodo

### ISSUE THREAD

**Issue by kammerer** [TGAC/brassica#629]
As stated in email from Thomas Alcock:

> I have just tried to re-request a DOI for the leaf mineral database. This didn’t seem to work, and I got an error message containing ‘failure code 401’ (see below). Do either of you know what might have caused this or have any suggestions to fix it? The BIP submission page still allows me to press ‘request doi’.

**Comment by kammerer** [comment]
It seems to be a Zenodo bug unless somebody removed the API key used currently by BIP.

**Comment by Nuanda** [comment]
Could it be that Zenodo detected "suspicious" description content (URLs) and rejected the submission in that fashion?

**Comment by Nuanda** [comment]
Another thing that comes to my mind is wrong handing of CR NL characters in Zenodo deposition metadata form for contributors - perhaps BIP tries to send all names as a single _Researcher_ entry and that makes Zenodo angry?

**Comment by teatree1212** [comment]
maybe it has detected that the entry is very similar to a previous entry and doesn't like that?

**Comment by Nuanda** [comment]
I have just tested exactly same metadata content on the Zenodo Sandbox and got no errors there. Though the Sandbox, as you have realized, looks a bit different compared to the production Zenodo instance.

I'll try to test if our official BIP API token is still valid in Zenodo production.

**Comment by teatree1212** [comment]
can you see whether Tom listed all contributors following the instructions beneath the box: to list each name in a single line ?

**Comment by Nuanda** [comment]
He has listed 15 names there. He has used a single line per each person. Anyway, this was not the issue :).

I have tested our API key, seems to be working.

**Comment by Nuanda** [comment]
It was old incorrect token used by BIP to access Zenodo. Reloaded the token to a correct one.

**Comment by Nuanda** [comment]
@kammerer So, I hope it is ok now to signal Thomas to retry the deposition.
