### ISSUE TITLE
Try to submit BIP Trial/Population back-link along with Zenodo metadata

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#633]
The idea is to have a URL that leads back from Zenodo deposition page directly to BIP. Even better - to the exact submitted object (either a PlantTrial or a PlantPopulation).

Idea sent by Thomas Alcock and @teatree1212.

**Comment by teatree1212** [comment]
question about this: of course the data has been in the database for a week officially before it can be submitted to Zenodo. It would be good - and I thought it is posisble- for the user to still alter the data in BIP( obviously not the stuff sent to Zenodo). So if it is altered, will it receive a new object identifier , which therefore breaks the direkt URL?
