### ISSUE TITLE
Dealing with finalized submissions without the submitted object

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#636]
It is possible to submit a submissions and then use API to delete the submitted object. BIP should be able to handle that well.

One clean solution would be to destroy related submission (and cascade-destroy its uploads) when a plant trial or a plant population is destroyed.

@kammerer What's your opinion?

**Comment by kammerer** [comment]
It definitely needs to be handled somehow, either by what you suggest or by blocking removal of such objects. I guess both solutions are OK.
