### ISSUE TITLE
Extend PT scoring template with PA.year_produced and make it obligatory

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#641]
@teatree1212: The year_produced information should be added to the accession in the plant_trial_scoring submission template, as this can explain variation in the data.

**Comment by Nuanda** [comment]
My question is: should a corresponding PA not be found in the BIP during the submission, a new PA should be created (as it happens at the moment) with the `year_produced` column set to the value provided by the user?

Also, should that value be required in case a given PA is missing and will be created?

**Comment by teatree1212** [comment]
PA and year_produced always need to be seen in tandem.  A value for year_produced should always be required.
I think you should even check that , if PA is present, is the combination of PA and year_produced   that is about to be submitted present?
It will probably actually lead to what may seem as duplicated PAs, but with different values for year_produced. A shame they are recorded in the same table.

so answer to 
Q1:
yes

Q2:
yes

bear in mind the comments above that
- the PA and year_produced *combination* should be checked for and submitted if not present.

**Comment by Nuanda** [comment]
Currently, after some discussion some time ago, we require both `plant_accession` and `originating_organisation` for each PA. The combination of these two must be unique. I understand now we should add the third column, `year_produced` to this combination?

**Comment by teatree1212** [comment]
yes, correct.

**Comment by Nuanda** [comment]
Again, this depends on the way we refactor the Population submission wizard and whether or not it will take the responsibility for PA registration. So this task will be either realised in PT submission or PP submission templates.

**Comment by Nuanda** [comment]
@nowakowski This is nothing new - you are going to do that in the course of the task we have discussed recently. The Population Submission mentioned above should soon be prepared to accept this 3-column-uniqueness as well.
