### ISSUE TITLE
scoring_unit_name nomenclature

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#654]
I have a question about the restrictions and consequences with regard to the submission of similar plant scoring unit names.

In the old cropStore database, the scoring unit name was dictated by a certain nomenclature:
which contains a lot of information ( which you can get when querying properly anyways), but also ensures the PSU_name's uniqueness.

I don't want future users to have to follow this nomenclature, as it is additional work and -hopefully- unneccessary:

How important is it that the PSU_name is unique?
Can we 
-somehow allow similar PSU_names, but which are associated to different Plant_Trials?
-Or automatically create a new hidden unique identifier for each PSU_name in the database that enables supposedly similar PSU_name entries?
- Or automatically add a prefix to the PSU_name that is submitted, mimicking the CropStore nomencalture of a PSU_name?
e.g. when the user submits a plant scoring unit in their template, such as p_000123, it would be changed by adding the <institute><YY>_PSU_name such as Nottingham16_p_000123. ( this could also serve as the hidden unique identifier)

**Comment by Nuanda** [comment]
I don't thinks it is important for BIP internal operations. So we can remove it and nothing breaks.

However, the user experience may suffer. The immediate consequence is that people are able to make exact copies of Plant Lines in BIP - there will be nothing to stop them from doing so. Apart from the obvious (and maybe not as crucial) things like having duplicated entries in the data tables, API query calls and front page searches, there are issues with submission forms.

The uniqueness requirement is there mainly for user's comfort (the DB does not care about that). When there is a form prompting the user to pick an existing Plant Line (such forms are in the Plant Population submission wizard), BIP will show two identical entries and there is no way the user can tell one PL from another.

What you propose by `but which are associated to different Plant_Trials` is actually extending the uniqueness requirement to a set of columns (we did that for PAs, if you remember, requiring the pair of pa and oo to be unique). This way we would require the pair of `plant_line_name

**Comment by teatree1212** [comment]
did you confuse plant_line_name with Plant_scoring_unit_name? I am talking about the identifier the closes to the actual trait score values. it can be that by chance different trials call their samples (plant_scoring_unit_names ) p_1, p_2.., but at the same time submit totally different accessions. What however can happen ( and would happen in the RIPR project, which is why I am asking), is that they have the same , (plant_scoring_unit_names ) p_1, p_2, and also the same accessions, but not necessarily the same plant_scoring_unit_names used for the same accessions. And it would be a different  PSU anyways. in the RIPR project, in theory, everything is submitted will be the same all the way down to the PA, which is the last similar information. On the level of the PSU, the different trials grow different plants, which they however can and have called plant 1, plant 2.. (p_1, p_2...)..

**Comment by Nuanda** [comment]
Ahhhh, I somehow got it totally wrong. Sorry for forcing you to explain it twice.

PSU's `scoring_unit_name` (aka `sample_id` in the template, not to confuse the users) is not required to be unique by BIP. You are able to resubmit `plant_1` or `p1` in different PT submissions.

**Comment by teatree1212** [comment]
great. that's all I needed to know then.  I suppose the plant scoring unit_names will always be displayed in context with more information (such as traits, accessions or trial_names or something)so that people will not mix them unintentionally.

**Comment by Nuanda** [comment]
I assume, that since PSU.scoring_unit_name is not required to be unique, I can close this issue/question.
