### ISSUE TITLE
taxonomy_terms

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#657]
Can you explain to me why the taxonomy_term_id is similar for many  different species recorded in table taxonomy_terms?

SELECT * FROM taxonomy_terms WHERE taxonomy_term_id=1;

**Comment by Nuanda** [comment]
The customary primary key for all records in BIP is called `id` (the `id` column in any table). `model_name_id` is a customary name for a foreign key when a record is related to the `model_name` table.

Therefore, here, TaxonomyTerm.taxonomy_term_id is a foreign key to the TaxonomyTerm table itself. We use such an auto-relation to model taxonomy trees. Hence, the value of `taxonomy_term_id` for a given record equals `id` of its parent in the TaxonomyTerm table.

The value of 1 means "Brassica" - therefore the immediate parent to many taxonomy units.

**Comment by Nuanda** [comment]
Since there are no follow up comments from @teatree1212 I understand I can close this one.
