### ISSUE TITLE
Submission show should  assume nothing about related records existence

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#664]
It is because the owner is able to API-delete them. The `submitted_object`s should be there, as destroying them should destroy the submission as well. However, other things may disappear (an example, which is already fixed: plant_population is mission for a plant trial submission).

Look for other examples and improve the submission show partials not to trip on cases like that.

**Comment by kammerer** [comment]
Submission show may also be displayed before submission is finalized, so it cannot expect submitted object to be found.
