### ISSUE TITLE
delete workshop material

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#666]
Could you please also delete my submissions related to the workshop? All my submissions are unimportant, so you can remove them all to be on the safe side.

**Comment by Nuanda** [comment]
@teatree1212 I somehow lost the workshop attendees list you sent me. Can you please send me (by email) again the names of the people who were there, so I don't delete something important by accident?

**Comment by teatree1212** [comment]
okay

**Comment by Nuanda** [comment]
Thanks. Done.
