### ISSUE TITLE
adding manual files

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#668]
I am trying to add manual files to the submissions/new  in case of the Plant population and the Plant scoring trial population. 

I did the following thing:
1) created a branch add_manuals
2)added files to new folder public/manuals/upload_population_submission 
                                  and public/manuals/upload_Trial_submission

3)added
= succeed'.' do
            = link_to 'here', 'manuals/upload_population_submission.pdf'.
to the file [submissions.en.yml](https://github.com/TGAC/brassica/blob/3bcfdebc04d275fe4e37dc51ed35604e8bbecfb7/config/locales/submissions.en.yml).
    following this style based on [about.html.haml](https://github.com/TGAC/brassica/blob/eebfffbb631170baebdda6f400d71fe41b09d057/app/views/application/about.html.haml), where you use in line 57
  = succeed '.' do
      = link_to 'in this diagram', 'images/models_complete.png'

4) loaded on local host and only got _= succeed'.' do = link_to 'here', 'manuals/upload_population_submission.pdf'. _ as text instead of a link to the file.

I understand that at the moment in the file it is just a multi-line string. I understand that the file types are different, so maybe it has something to do with this. But I don't know enough to google with the correct search words. So how do would I go about to do this simple edit?

**Comment by teatree1212** [comment]
I forgot to push to the branch. Will do tomorrow, please ignore until then.

**Comment by Nuanda** [comment]
The `.yml` (aka locales) files have a different markup. I can help with that - but have you committed the manual pdf itself to git?

**Comment by teatree1212** [comment]
pushed

**Comment by teatree1212** [comment]
I know it is easy for you to fix, if you find some time to explain it briefly to me, that would be great (:

**Comment by Nuanda** [comment]
Moving this discussion to a PR.
