### ISSUE TITLE
Hints for Windows users in example client docs

### ISSUE THREAD

**Issue by kammerer** [TGAC/brassica#669]
Two things which come to mind:
1. Ruby installation 
2. [SSL certs setup](http://stackoverflow.com/questions/5720484/how-to-solve-certificate-verify-failed-on-windows)

**Comment by teatree1212** [comment]
look at the manual I produced for the ruby installation for windows users
[upload_population_submission.pdf](https://github.com/TGAC/brassica/files/493889/upload_population_submission.pdf)

**Comment by kammerer** [comment]
Ruby installation is covered in the submission manual PDF. RubyInstaller, suggested for Windows systems, for some time now includes SSL certificate bundle so there is no need for additional setup.
