### ISSUE TITLE
achnowledgements

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#673]
could you please add an "acknowledgements" section to the About us page and add:

This work was supported by UK Biotechnology and Biological Sciences Research Council as part of the BBSRC Renewable Industrial Products from Rapeseed (RIPR) Programme (BB/L002124/1)

**Comment by Nuanda** [comment]
Done. Can you, in return, ask EI website admins to change some information here: http://www.earlham.ac.uk/brassica-information-portal#Collaborators-4.

Changes:
 - please name three people for Spectrum Informatyka, as it is done here: https://bip.earlham.ac.uk/about (Tomasz Gubała, Tomasz Szymczyszyn, Piotr Nowakowski, remove Mr Chucherko)
 - maybe change Spectrum Informatyka to Spectrum IT (this is the name we use for EN lang communications) - the link may stay as it is now.

**Comment by Nuanda** [comment]
BTW this https://twitter.com/BrassicaP has the old BIP URL in the left panel.

**Comment by teatree1212** [comment]
thanks, will change that!

**Comment by teatree1212** [comment]
all resolved
