### ISSUE TITLE
added impact section to about

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#674]
I edited the about section a bit following Wiktors request to include BIPs impact. While doing so I also took the liberty to name CropStoreDB again and refer to links related to the Brassica community in general.
have merged the branch impact_stuff with master but not yet deleted it, in case you disagree with something.
But I can't see it yet in the life version. Do you have an approval step in between?
https://github.com/TGAC/brassica/blob/master/app/views/application/about.html.haml

**Comment by Nuanda** [comment]
Yes we do - it's the pull requests mechanism. Please create a pull request (here on GitHub) with your new branch - then, name me as the reviewer and await code review ;).

**Comment by Nuanda** [comment]
Reviewer == assignee (in the PR view)

**Comment by Nuanda** [comment]
Deployed to production.
