### ISSUE TITLE
pedigree information across database

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#676]
In the API description I came across multiple pedigree fields that are supposed to give the same information:

Can you explain to me why you created the
fathered_descendants_id 
mothered_descendants_id 

in what relationship are they to female_parent / male_parent (plant varieties)
and male_parent_line_id and female_parent_line_id? (plant accessions)

**Comment by teatree1212** [comment]
more observations about this topic:
Pedigree information ( as ids) occurs many places in BIP.  It is not clear to me where the user can actually submit new parental lines in the case of a population submission, as the table hosts ids, which I am not sure where they come from. It seems that plant_lines also only hosts IDs.

**Comment by Nuanda** [comment]
@teatree1212 Sorry for a late replay, I was very busy with other appointments. Regarding your question, I think it all stems from the original CS schema, but I'll let @nowakowski to explain, since he was in charge of modeling CS -> BIP data transition.

**Comment by nowakowski** [comment]
These fields (`fathered_descendants` and `mothered_descendants`) are the flip side of the PlantPopulation -> PlantLine relation which was originally present in CropStore DB. Each population has a 'mother' and a 'father' plant line (linked via `male_parent_line_id` and `female_parent_line_id` respectively); therefore each PlantLine has a list of "fathered" and "mothered" populations (awkward naming but I had to think of something...) The UI presents the identifiers of these populations as `fathered_descedant_ids` and `mothered_descendant_ids` (both are simple lists of integers).

Hope this clarifies the issue from the DB PoV.

**Comment by teatree1212** [comment]
Are you saying: children lines with certain registered parents can be the parents of a new population? 
Wouldn't that kind of "child/parent"-line then have 2 identifiers? one would be them as a parent and one would be them as being themselves further "downstream" when liking with accessions?

**Comment by nowakowski** [comment]
Well, any line can be the parent of a new population (or an arbitrary number of new populations). However, for the resulting population to become the parent of further populations it would first need to be registered as a new `PlantLine`. Only `PlantLines` can have children populations; there is no `PlantPopulation` -> `PlantPopulation` relation and likewise, there is no notion of "children lines" (only "children populations"). Perhaps the model is missing a PL->PL link where `PlantLines` coult be directly registered as ancestors of other `PlantLines`?

**Comment by Nuanda** [comment]
BTW I see there is a mistake in the API docs saying these two are PL -> PL relations, which is not the case (they are PL -> PP relations). I'll fix it in a minute.

**Comment by teatree1212** [comment]
@nowakowski   Is the content in fathered_descendants_id =  the content in the male_parent_line_id ?

**Comment by teatree1212** [comment]
I suppose it is, as you said that one is the "flipside" of the other- so just a change in perspectives.
So  by this sentence below
"However, for the resulting population to become the parent of further populations it would first need to be registered as a new PlantLine."
Do you actually mean:
"However, for *the resulting PlantLine from* a population to become the parent of further populations it would first need to be registered as a new PlantLine."

They should definitely be connected, but I understand that they are connected via the PP, as the PP specifies how they actually became the "parent" - whether the exercise was actual crossing between to PLs or only one PL exposed to radiation/chemicals producing new .

**Comment by nowakowski** [comment]
Regarding your first question - yep, that's exactly the content you're asking about.

With respect to the second question - I think (although I cannot be sure) that this was exactly the logic which guided the creators of the original CropStore DB schema. We start off with two PlantLines, then register a PlantPopulation which is a result of crossbreeding said lines (or perhaps is only linked to a single PlantLine in case of radiation/chems/etc.), then register a new PlantLine which is based on (or "_from_") the new PlantPopulation. As a result, PlantLines are related through PlantPopulations.
