### ISSUE TITLE
API query RIPR trial

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#677]
I am querying in python:

import requests
import json

r = requests.get('https://bip.earlham.ac.uk/api/v1/plant_trials?plant_trial[query][plant_trial_name]=U.Nottm_2016_RIPRleafminerals_REMLmeans',headers ={'X-BIP-Api-Key':'my_API_key'})

 and only get:
{u'meta': {u'per_page': 50, u'page': 1, u'total_count': 0}, u'plant_trials': []}

in response.

When querying for a different trial name:

import requests
import json

r = requests.get('https://bip.earlham.ac.uk/api/v1/plant_trials?plant_trial[query][plant_trial_name]=hri_1996_gr_01',headers ={'X-BIP-Api-Key':'my_API_key'})

I get a response with content and metadata on the trial. Here its beginnings:

{u'meta': {u'per_page': 50, u'page': 1, u'total_count': 1}, u'plant_trials': [{u'trial_year': u'1996', u'data_provenance': u'EU project AIR3 - CT920463; http://documents.plant.wur.nl/cgn/pgr/brasedb/brasair.htm#results; "AIR results for BrasEDB.xls" downloaded from http://documents.plant.wur.nl/cgn/pgr/brasedb/brasair.htm', u'design_type': None, u'terrain': u'growth room', u'project_descriptor': u'AIR3 - CT920463', u'plant_trial_name': u'hri_1996_gr_01', u'longitude': u'-1.6', u'layout_content_type': None, u'statistical_factors': None, u'id': 2, u'place_name': u'Wellesbourne', u'published_on': u'2015-07-22T11:33:22.871Z', u'date_entered': u'2010-05-05', u'processed_trait_dataset_ids': [], u'alti...

I am sure I didn't misspell the trial name, as I have copied and pasted the name.

Going about it differently and querying for the trial_year:

r = requests.get('https://bip.earlham.ac.uk/api/v1/plant_trials?plant_trial[query][trial_year]=2014',headers ={'X-BIP-Api-Key':'my_API_key'})

I get the two trials ( including my trial of interest [U.Nottm_2016_RIPRleafminerals_REMLmean])
displayed.

Why is this particular plant_trial_name field not accessible via the API?

**Comment by teatree1212** [comment]
there is a space in the name. Best to remove any spaces after people submit plant trial names

**Comment by teatree1212** [comment]
2) it would also be good to be able to use the API  in a "search for strings that start with xyz"

3) We talked about this before:  include access to IDs, so people can search using IDs.
If you consider these things development heavy, maybe put them on a to-do list?

**Comment by Nuanda** [comment]
1. Leading/trailing spaces in names. Good suggestion. Should I remove these from the RIPR trial names in production BIP?

2. You can do that right now - please see https://bip.earlham.ac.uk/api_documentation#searching-for-data - an example:

```
curl -g -X GET "https://bip.earlham.ac.uk/api/v1/plant_trials?plant_trial[fetch]=RIPR" -H "X-BIP-Api-Key: YOURKEY" -H "Content-Type: application/json"
```

fetches the three RIPR trials.

3. There is access to ID, every json element returned by the API has the 'id' attribute. And you can use it to search for records as well, like:

```
curl -g -X GET "https://bip.earlham.ac.uk/api/v1/plant_varieties?plant_variety[query][id]=15" -H "X-BIP-Api-Key: YOURKEY" -H "Content-Type: application/json"
```

returns the PV of id = 15.

**Comment by kammerer** [comment]
I have to admit that I am guilty of adding these spaces :| I did that because of the requirement for name uniqueness when I was trying to resubmit data. Then, I obviously forget about that.

Anyway, I think we should strip trailing/leading spaces from user input.

**Comment by teatree1212** [comment]
Never mind @kammerer  (:
could 2 and 3 be in the API documentation?

**Comment by Nuanda** [comment]
1. Fixed.

2 and 3. Should we add a section in the API Docs which will discuss the "technique" of looking for IDs in returned JSONs and used them to fetch further records from related tables?

**Comment by teatree1212** [comment]
2 and 3: that is a good idea @Nuanda
