### ISSUE TITLE
Querying field from trait table: permission denied

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#678]
I am test-querying  the following:

brassica=> SELECT * FROM traits;
ERROR:  permission denied for relation traits

Why is that?

My big query wants to get distinct information from many tables, including the `traits.name` field

SELECT PT.plant_trial_name, 
       TS.score_value, 
       PA.plant_accession, 
       PL.plant_line_name, PL.sequence_identifier, 
       TD.descriptor_name, TD.units_of_measurements,
       PP.plant_part,
       T.name

      
	FROM plant_trials PT 
		JOIN plant_scoring_units PSU 
		ON PT.id=PSU.plant_trial_id 
		
			JOIN trait_scores TS
			ON TS.plant_scoring_unit_id=PSU.id
			
			      JOIN plant_accessions PA
			      ON PSU.plant_accession_id =PA.id

				  JOIN plant_lines PL
				  ON PL.id=PA.plant_line_id

					JOIN trait_descriptors TD
					ON TD.id=TS.trait_descriptor_id

						JOIN plant_parts PP
						ON PP.id=TD.plant_part_id
 
                                                     JOIN traits T
                                                      On T.id=TD.trait_id

			WHERE PT.plant_trial_name = 'U.Nottm_2016_RIPRleafminerals_REMLmeans ';

**Comment by nowakowski** [comment]
Hello. Your user was missing the SELECT grant for traits. Unsure why this occurred but I believe I have fixed it. Sorry for the inconvenience.

**Comment by teatree1212** [comment]
thanks! no worries!
