### ISSUE TITLE
Problem with population removal

### ISSUE THREAD

**Issue by wjurkowski** [TGAC/brassica#700]
I can't remove a mock population. When running

ruby population_cleanup.rb RIPR_test_Wiktor mykey. 

I get: "Plant Population RIPR_test_Wiktor not found or it does not belong to you. Exiting."

**Comment by Nuanda** [comment]
The text is a bit misleading, but the fact is that you can no longer remove that population. It is not revocable anymore, since it is both published and adequately old.

**Comment by Nuanda** [comment]
Should I remove it from the DB by hand?

**Comment by wjurkowski** [comment]
Ah, forgot about the 1 week grace period that I got associated with traits
only...

**Comment by wjurkowski** [comment]
yes, please delete it!
