### ISSUE TITLE
Make establishing_organisation required for PP

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#701]
@teatree1212 Annemarie, in #494 you wrote:

> Note: for poulation submission, the establising_organisation needs to be mad compulsory metadata meet DOI assignemt criteria.

Should we make this column required for all PPs submitted in the future (either with the submission wizard or via the API)?

**Comment by wjurkowski** [comment]
yes, there always should be someone behind it

**Comment by Nuanda** [comment]
@nowakowski Piotr, this requires the following:

- [ ] check if there are PPs with no establishing_organisation set, if found - report them here
- [ ] add the DB constraint and the AR model validation
- [ ] denote the establishing_organisation field as mandatory in the API docs page
- [ ] test if API-creating a PP with no establishing_organisation returns adequate error message
- [ ] extend the 1st step of the PP submission wizard with establishing_organisation field (both the Step01ContentForm class and the corresponding view)
- [ ] make this step01 field required in the submission wizard view
- [ ] remember - people have saved unfinished PP submissions on production: make sure the PlantTrialFinalizer (and the entire submission wizard) behaves correctly when encountering a PP with no establishing_organisation - it should return the user to the 1st step of the procedure and ask her to provide that additional field.

**Comment by nowakowski** [comment]
With regard to item (1), the following PPs have no assigned `establishing_organisation` (field value is NULL).

@wjurkowski - I can manually update these records (and in fact must do so prior to adding DB constraints), but I need suitable organisation names. Can you assist?

- BniTIF2_01
- BnaPIIT_01
- BolBOF2_00
- BnaSDDH_00
- BolTBDH_00
- BraCKDH_00
- BraIRRI_01
- BolDCC_01
- BjuHVDH_01
- BolLAIT_01
- BraIRRI_00
- BraVCS3M_01
- BraDCC_01
- BniCCSL_00
- BnaEVDH_00
- BnaHSDH_02
- BraIRRI_02
- BraIRRI_03
- BraJWF3_01
- BnaWTF3_00
- Bol8CF3_01
- BolBKF2_00
- BnaSDDH_01
- BnaDSDH_00
- BolNGDH_01
- BnaHSDH_01
- BolAGSL_02
- BolAGDH_04
- BolAGDH_03
- BolTBDH_01
- BjuHVDH_00
- BnaHSDH_00
- BolAGSL_01
- BolAGSL_00
- BnaDOF3_00
- BnaWTF3_01
- BnaWNDH_00
- BnaNWDH_01
- BnaDCC_01
- Bol8CF3_00

**Comment by teatree1212** [comment]
What other metadata is associated with them? They seem to all be PPs that were used in linkage map -generation.

**Comment by nowakowski** [comment]
There's some additional data, but not a lot - see [populations.txt](https://github.com/TGAC/brassica/files/750350/populations.txt) for an SQL data dump.

**Comment by teatree1212** [comment]
You know what, I just had a quick look at this but my initial thoughts are : This would require quite  some time of curation. Sometimes, they point at publications and when reading these, one would probably find out who was in charge or made them, and if not, one would have to contact the people. Could you just fill the establishing_organisation with unspecified organisation as a keyword for us to know that this needs reviewing in the future? I can't do that now.

**Comment by nowakowski** [comment]
@teatree1212 Forthwith.

**Comment by teatree1212** [comment]
Maybe think of not giving the unspecified organisation term as an option for users to add as a content themselves, when they are submitting ( can this be excluded from the elasticsearch or sth like that?)

**Comment by nowakowski** [comment]
Given that our data model does not (currently) cover organisations as a standalone entity, we can't offer a drop-down list of "known organisations" in the UI. Consequently, the user is free to type anything in the establishing_organisation field when submitting a new record.

While I can add a validation which would exclude `unspecified organisation` (exact string match) as a valid value of the field, it would be fairly easy to evade this check, e.g. by adding extra whitespace, swapping 'unspecified' for 'unknown', etc. I would not recommend going down this path - but perhaps it's not necessary given that there are fewer than 200 plant populations in the DB?

**Comment by teatree1212** [comment]
Okay, If this function is not available anyways, I will hope that people put in the right name in. 
However, It hink in the future this should not  be a freetext field. Whether someone puts in an acronym or the full name or- in case this is case sensitive as well- .. ETC, this 
Also, what is defined as Institute in the trial submission step 1 ( dont have the schema in front of me) should often if not always be the establishing_organisation. Do you see there being the same acronyms as values the PTinstitute(?) and PPestablishing_organisation fields?

**Comment by nowakowski** [comment]
How about we add an optional drop-down listing all _existing_ values of `establishing_organisation` currently in the DB (less 'unspecified organisation') but also permitting the user to type in their own name?

Regarding the institute name, yes, I see some overlap but it's not always the case. There are many records where institute name has nothing to do with est.org. :(

**Comment by teatree1212** [comment]
You mean exactly like the way it is being done during trial_submission? I think that is a good Idea.

Oh no .. I can’t look at it myself atm and make sense of it. It might still be reasonable content… (:
