### ISSUE TITLE
Add description of columns in the template files 

### ISSUE THREAD

**Issue by wjurkowski** [TGAC/brassica#708]
Request from BIP users: when the template for data collection is generated and passed on someone else, it is difficult to keep track what is the expected content of specific columns. It would be handy to have either additional sheet in the spreadsheet or a header section with brief descriptions and references to e.g. user manual.

**Comment by kammerer** [comment]
As these templates are CSV files it is not possible to have additional sheet. The only way to do that without switching to a more complex file format is to add descriptions in the second header row and make parsers ignore that row.
