### ISSUE TITLE
Poorly worded request about deployment in README

### ISSUE THREAD

**Issue by peterjc** [TGAC/brassica#712]
Your README file contains:

> It is a Rails web application is released as a free and open source project
> (see the LICENSE.txt file). The underlying database schema is derived
> from the CropStoreDB schema ver.7, with the original version developed
> by Graham King and Pierre Carion at Rothamsted Research.
>
> Apart from the LICENSE, EI explicitly requests any party that wishes to
> deploy a copy (modified or not) of BIP on their own servers, to contact,
> and obtain permission to do so. For that, please contact bip@earlham.ac.uk.
>  If you are interested in contributing to the project, ...

Given that the ``LICENSE.txt`` file is *GNU General Public License v3.0*, I think this is poorly worded (request vs obtain permission), and I suggest:

> While not required under the LICENSE, the EI explicitly requests any
party that wishes to deploy a copy (modified or not) of BIP on their own
servers, please inform bip@earlham.ac.uk.

i.e. Make it clearer this is a non-legally binding request, and this is not required under the open source license you have selected.

If this is to help measure the software impact (to help with funding etc), maybe say so?

**Comment by Nuanda** [comment]
@teatree1212 Please look into that one and check what exactly should be written there.

**Comment by wjurkowski** [comment]
@peterjc Thanks for the feedback!

**Comment by teatree1212** [comment]
@peterjc thank-you so much! That was indeed a controvers statement.. it's changed now.

**Comment by peterjc** [comment]
I'd still remove the "obtain permission" bit, however this is a lot clearer now thank you:

> While not required under the LICENSE, Earlham Institute explicitly asks any party that wishes to deploy a copy (modified or not) of BIP on their own servers, to contact, and obtain permission to do so. For that, please contact bip@earlham.ac.uk. According to the LICENSE, contacting us is not a legally binding requirement, but it aims to help measure the software impact and stay in contact with users for continuous software improvement. If you are interested in contributing to the project, for example by adding any analytics tools, please contact us, too. We are looking forward any feedback! For further contact information on people behind the project or the database itself, please see the about us section

**Comment by teatree1212** [comment]
yes, agreed. WIll do so now.

**Comment by teatree1212** [comment]
Actually, this bit of text was in the README before my time. I don't know for what reason it is in there and whether it is a default politcy of the institute. Then it would be contradictory with the choice of licence.

**Comment by teatree1212** [comment]
all done
