### ISSUE TITLE
Remove dummy Accessions and associated dummy lines + other fields

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#723]
From last year there have been left some relict dummy Accessions in BIP that were created during the making of the workshop material around that time ( entry date: 2016-09-06, Entered-by: me) . 

Could you remove them? (+ organisation, Year produced )
They don't seem to be associated to a population.
here: https://bip.earlham.ac.uk/data_tables?fetch=JIC09&model=plant_accessions
Thanks!

**Comment by wjurkowski** [comment]
The same with me - could you remove my dummy submission please?

**Comment by Nuanda** [comment]
@teatree1212 Done.

@wjurkowski You have 9 submissions in the system, 2 finalized. I believe the non finalized ones you can remove by yourself in the BIP UI. Should I remove the finalized 2?

**Comment by wjurkowski** [comment]
Yes, please. Next time will remember to do it within the grace period

Thanks
W

**Comment by Nuanda** [comment]
Done.
