### ISSUE TITLE
remove trait descriptor 

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#740]
in the traits table as it is visible on the [website](https://bip.earlham.ac.uk/data_tables?group=true&model=trait_descriptors), trait number 6 is not actually a trait but the header for one of the sheets I passed on to you containing the traits.
https://bip.earlham.ac.uk/data_tables?group=true&model=trait_descriptors

please remove.
![screen shot 2017-08-24 at 15 42 32](https://user-images.githubusercontent.com/17452217/29672265-a6318c8c-88e3-11e7-80c5-c362589b5bd6.png)

**Comment by Nuanda** [comment]
Done. Thanks for reporting!
